<?php

namespace  Test\Feature;

use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;

class AttachmentTest extends TestCase{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate');
    }

    public function testIncorrectData (){
        $response = $this->post(route('attachments.store'), [
            'attachable_type' => 'popopo',
            'attachable_id' => 3,
            'image' => 'demo',
        ]);
        $response->assertStatus(422);
    }
}
